# Generated by Django 2.2.6 on 2019-10-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20191009_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.Participant'),
        ),
    ]
