# Generated by Django 2.2.6 on 2019-10-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20191009_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='was_successful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
