# Generated by Django 2.2.8 on 2020-07-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20191010_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='mood',
        ),
    ]
