# Generated by Django 2.2.8 on 2020-07-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_remove_vote_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meeting.Topic'),
        ),
    ]
