# Generated by Django 2.2.6 on 2019-10-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0008_auto_20191010_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('actions', models.ManyToManyField(to='meeting.Action')),
            ],
        ),
    ]
