# Generated by Django 2.2.8 on 2020-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamgoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgoal',
            name='actions',
            field=models.ManyToManyField(blank=True, to='meeting.Action'),
        ),
    ]
